export const REGISTER_USER_INITIATED = 'REGISTER_USER_INITIATED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_ENTRY_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ENTRY_INITIATED = 'CREATE_ARTICLE_INITIATED';
export const CREATE_ENTRY_ERROR = 'CREATE_ARTICLE_ERROR';

export const GET_SPECIFIC_ENTRY_SUCCESS = 'GET_SPECIFIC_ARTICLE_SUCCESS';
export const GET_SPECIFIC_ENTRY_INITIATED = 'GET_SPECIFIC_ARTICLE_INITIATED';
export const GET_ALL_ENTRIES_SUCCESS = 'GET_ALL_ARTICLES_SUCCESS';

export const EDIT_ENTRY_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ENTRY_ERROR = 'EDIT_ARTICLE_ERROR';
export const EDIT_ENTRY_INITIATED = 'EDIT_ARTICLE_INITIATED';
